neogpt:
  VERSION: 0.1.0-beta
  ENV: development
  PERSONA: default
  UI: false
  MODEL_TYPE: mistral
  EXPORT_DATE: '2024-01-07 15:06:23'
  LICENSE: MIT
model:
  MODEL_NAME: TinyLlama/TinyLlama-1.1B-Chat-v0.6
  MODEL_FILE: None
  EMBEDDING_MODEL: sentence-transformers/all-MiniLM-L12-v2
  INGEST_THREADS: 8
  MAX_TOKEN_LENGTH: 8192
  N_GPU_LAYERS: 40
database:
  PARENT_DB_DIRECTORY: db
directories:
  SOURCE_DIR: documents
  WORKSPACE_DIRECTORY: workspace
  MODEL_DIRECTORY: models
memory:
  DEFAULT_MEMORY_KEY: 2
logs:
  LOG_FOLDER: logs
  BUILDER_LOG_FILE: builder.log
  NEOGPT_LOG_FILE: neogpt.log
