site_name: NeoGPT 🤖
docs_dir: 'content'
repo_url: https://github.com/neokd/NeoGPT
repo_name: neokd/NeoGPT
edit_uri: https://github.com/neokd/NeoGPT/tree/main/docs

theme:
    name: material
    
    font: 
      text: Nunito
    icon:
      repo: fontawesome/brands/github
      previous: fontawesome/solid/angle-left
      next: fontawesome/solid/angle-right
      logo: material/bookshelf
      admonition:
        note: fontawesome/solid/note-sticky
        abstract: fontawesome/solid/book
        info: fontawesome/solid/circle-info
        tip: fontawesome/solid/fire
        success: fontawesome/solid/check
        question: fontawesome/solid/circle-question
        warning: fontawesome/solid/triangle-exclamation
        failure: fontawesome/solid/bomb
        danger: fontawesome/solid/skull
        bug: fontawesome/solid/robot
        example: fontawesome/solid/flask
        quote: fontawesome/solid/quote-left
    features:
      - navigation.tabs
      - navigation.sections
      - search.share
      # - toc.integrate
      - navigation.top
      - search.suggest
      - search.highlight
      - search.share
      - content.tabs.link
      - content.code.annotation
      - content.code.copy
      - content.action.edit
      - navigation.footer
    palette:
      - scheme: default
        toggle : 
          icon: material/weather-sunny
          name: Switch to dark mode
        primary: deep purple
        accent: deep purple
      - scheme: slate
        toggle : 
          icon: material/weather-night
          name: Switch to light mode
        primary: black
        accent: deep purple
 
nav:
  - Home: index.md
  - Docs:
    - Installation: installation.md
    - Builder: builder.md
    - Run NeoGPT: neogpt.md
    - Advanced: 
        - Configuration: advance/configuration.md

extra_css:
  - stylesheets/custom.css


markdown_extensions:
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets


plugins:
  - termynal
  - search 
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
    

copyright: Copyright &copy; 2023 neokd

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/neokd/NeoGPT
      name: Github
      
    - icon:  fontawesome/brands/discord
      link: https://discord.gg/7xU954VYv
      name: Discord
  generator: false

